spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${username}
    password: ${dbpassword}


  # JPA & Hibernate ??
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # ???? SQL ??? ??? ?????.
        format_sql: true # SQL ??? ?? ?? ??????.
        default_batch_fetch_size: 100 # N+1 ?? ??? ?? ??
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt:
  # myChatServerAccessTokenmyChatServerAccessTokenmyChatServerAccessToken
  secretKey: 'bXlDaGF0U2VydmVyQWNjZXNzVG9rZW5teUNoYXRTZXJ2ZXJBY2Nlc3NUb2tlbm15Q2hhdFNlcnZlckFjY2Vzc1Rva2Vu'
  expiration: 3000 # 3000분